FROM debian:buster-slim

LABEL maintainer Travis CI GmbH <support+travis-app-docker-images@travis-ci.com>


RUN ( \
   mkdir -p /app; \
)
WORKDIR /app
COPY . /app


RUN ( \
  apt-get update; \
  # update to deb 10.8
  apt-get upgrade -y ; \
  apt-get install -y build-essential git libpq-dev curl postgresql-client perl-modules; \
  rm -rf /var/lib/apt/lists/* ; \
  /app/script/install-sqitch; \
  apt-get remove -y build-essential git libpq-dev gcc g++; \
  apt-get -y autoremove; \
)

