database_defaults: &database_defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

development:
  log_level: fatal
  logs_database:
    <<: *database_defaults

test:
  log_level: fatal
  logs_database:
    <<: *database_defaults
