#!/usr/bin/env ruby

min_id = Integer(ARGV.fetch(0))
max_id = Integer(ARGV.fetch(1))
end_id = max_id
begin_id = max_id
step = Integer(ARGV.fetch(2, '1000000'))

$LOAD_PATH << 'lib'

require 'bundler/setup'
require 'travis/logs/aggregate'

$stdout.sync = true
$stderr.sync = true

Travis.logger.info(
  'working through range',
  min_id: min_id, max_id: max_id, step: step
)

app = Travis::Logs::Aggregate.new
app.setup

Travis.logger.info('starting loop')
loop do
  break if end_id <= min_id
  begin_id = end_id - step - 1

  Travis.logger.info(
    'aggregate_logs!',
    begin_id: begin_id, end_id: end_id
  )
  app.aggregate_logs!([begin_id, end_id])

  end_id = begin_id + 1
end
