#!/usr/bin/env ruby
libdir = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'bundler/setup'
require 'travis/logs/aggregate'

$stdout.sync = true
$stderr.sync = true

app = Travis::Logs::Aggregate.new
app.setup
app.run_ranges
