#!/usr/bin/env ruby

$LOAD_PATH << 'lib'

require 'bundler/setup'
require 'travis/logs/aggregate'

$stdout.sync = true
$stderr.sync = true

end_id = Integer(ARGV.fetch(0))
range_size = Integer(ARGV.fetch(1, '1000000'))
begin_id = end_id
$stderr.puts "---> working back from end=#{end_id} range_size=#{range_size}"

app = Travis::Logs::Aggregate.new
$stderr.puts "---> Setting up"
app.setup

$stderr.puts "---> Starting loop"
loop do
  break if end_id <= 0
  begin_id = end_id - range_size - 1
  $stdout.puts "---> id_range=#{begin_id}-#{end_id}"
  app.aggregate_logs!([begin_id, end_id])
  end_id = begin_id + 1
end
