#!/usr/bin/env ruby
# frozen_string_literal: true

libdir = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'pry'
require 'travis'
require 'travis/logs'

Pry.config.prompt = Pry::SIMPLE_PROMPT
Pry.start(Pry.toplevel_binding)
