#!/usr/bin/env ruby
libdir = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'bundler/setup'
require 'pry'
require 'travis/logs'

Pry.config.prompt = Pry::SIMPLE_PROMPT
Pry.start(Pry.toplevel_binding)
