#!/usr/bin/env ruby

require 'bundler/setup'
require 'travis'
Travis::Database.connect

sql = <<-sql
  SELECT pgn.nspname, relkind, relname, pg_size_pretty(relpages::bigint * 8 * 1024) AS size,
    CASE
      WHEN relkind = 't'
        THEN (SELECT pgd.relname FROM pg_class pgd WHERE pgd.reltoastrelid = pg.oid)
      WHEN nspname = 'pg_toast' AND relkind = 'i'
        THEN (SELECT pgt.relname FROM pg_class pgt WHERE SUBSTRING(pgt.relname FROM 10) = REPLACE(SUBSTRING(pg.relname FROM 10), '_index', ''))
        ELSE (SELECT pgc.relname FROM pg_class pgc WHERE pg.reltoastrelid = pgc.oid)
    END::varchar AS refrelname,
    CASE
      WHEN nspname = 'pg_toast' AND relkind = 'i'
        THEN (SELECT pgts.relname FROM pg_class pgts WHERE pgts.reltoastrelid = (SELECT pgt.oid FROM pg_class pgt WHERE SUBSTRING(pgt.relname FROM 10) = REPLACE(SUBSTRING(pg.relname FROM 10), '_index', '')))
    END AS relidxrefrelname
    FROM pg_class pg, pg_namespace pgn
    WHERE pg.relnamespace = pgn.oid AND pgn.nspname NOT IN ('information_schema', 'pg_catalog')
    ORDER BY pg_relation_size(pg.oid) DESC
    LIMIT 20;
sql

data = ActiveRecord::Base.connection.select_all(sql)
data.each { |row| row['name'] = "#{row['nspname']}.#{row['relname']}" }
max = %w(size name refrelname).map { |key| data.map { |row| row[key].to_s.size }.max }
rows = data.map { |row| "| #{row['size'].rjust(max[0])} | #{row['name'].ljust(max[1])} | #{row['refrelname'].to_s.ljust(max[2])} |" }

line = "+#{max.map { |count| '-' * (count + 2) }.join('+')}+"
puts line, rows, line
