#!/usr/bin/env ruby
# frozen_string_literal: true

libdir = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'travis/logs/receive'

$stdout.sync = true

app = Travis::Logs::Receive.new
Travis.logger.info('setting up log parts processor')
app.setup
Travis.logger.info('running log parts processor')
app.run
