#!/usr/bin/env ruby
libdir = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'bundler/setup'
require 'travis/logs/receive'

$stdout.sync = true

app = Travis::Logs::Receive.new
app.setup
app.run
