#!/bin/bash
cd "$(dirname "$0")/.."
[ $PORT ]     || PORT=5555
[ $RACK_ENV ] || RACK_ENV=development

cmd="bundle exec puma -I lib -p $PORT -t ${PUMA_MIN_THREADS:-8}:${PUMA_MAX_THREADS:-12}"
[[ $RACK_ENV == "development" ]] && exec rerun -p '**/*.{rb,ru}' "$cmd -o 127.0.0.1"
exec $cmd
