#!/usr/bin/env ruby

require 'bundler/setup'
require 'travis'
require 'optparse'

$stdout.sync = true

Travis.config.log_level = :info
Travis::Database.connect
ActiveRecord::Base.logger.level = Logger::ERROR

def http
  Faraday.new(ssl: Travis.config.ssl.compact) do |f|
    f.request :url_encoded
    f.adapter :net_http
  end
end

def verify(log)
  puts "Verifying id: #{log.id}, job_id: #{log.job_id}"
  response = http.get("http://archive.travis-ci.org/jobs/#{log.job_id}/log.txt")
  actual   = response.headers['content-length'].try(:to_i)
  expected = log.content.bytesize.to_i

  if response.status == 200 && actual == expected
    true
  else
    log.update_attributes!(archive_verified: false)
    false
  end

rescue Faraday::Error => e
  puts "Could not verify log id:#{log.id}, job_id: #{log.job_id} #{e.message}"
  false
end

def purge(from, to, options = {})
  Artifact.find_each(conditions: ['id BETWEEN ? AND ?', from, to], batch_size: 5) do |log|
    next unless verify(log)
    puts "Purging log: id: #{log.id}, job_id: #{log.job_id}"
    log.destroy unless options[:dry]
  end
end


options = {}

OptionParser.new do |o|
  o.on('-f FROM', '--from FROM') { |v| options[:from] = v }
  o.on('-t TO', '--to TO')       { |v| options[:to]   = v }
  o.on('-d', '--dry', 'Boolean') { |v| options[:dry]  = v }
  o.parse!
end

from = options[:from] || ARGV[0] || 0
to   = options[:to]   || ARGV[1] || 3280461

puts "Going to purge logs for ids #{from}-#{to} #{'(dry run)' if options[:dry]}"
purge(from.to_i, to.to_i, dry: options[:dry])

