#!/usr/bin/env ruby

require 'bundler/setup'
require 'travis'

$stdout.sync = true

Travis.config.log_level = :info
Travis::Database.connect
ActiveRecord::Base.logger.level = Logger::ERROR

def http
  Faraday.new(ssl: Travis.config.ssl.compact) do |f|
    f.request :url_encoded
    f.adapter :net_http
  end
end

def verify(log)
  puts "verifying id: #{log.id}, job_id: #{log.job_id}"
  response = http.get("http://archive.travis-ci.org/jobs/#{log.job_id}/log.txt")
  actual   = response.headers['content-length'].try(:to_i)
  expected = log.content.bytesize.to_i

  if response.status == 200 && actual == expected
    true
  else
    log.update_attributes!(archive_verified: false)
    false
  end

rescue Faraday::Error => e
  puts "could not verify log id:#{log.id}, job_id: #{log.job_id} #{e.message}"
  false
end

def purge(from, to)
  Artifact.find_each(conditions: ['id BETWEEN ? AND ?', from, to], batch_size: 5) do |log|
    next unless verify(log)
    puts "purging: id: #{log.id}, job_id: #{log.job_id}"
    log.destroy
  end
end

from = ENV['FROM'] || 0
to = ENV['TO'] || 3280461
purge(from.to_i, to.to_i)

